version: '3.1'

services:
  postgres:
    container_name: code_rocks_postgres
    image: postgres:latest
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env

volumes:
  postgres:
